---
- name: Install and remove apt packages
  include: apt.yml
  become: true
  tags:
    - install-base
    - apt

- name: Install and remove python packages
  include: python.yml
  become: false
  tags:
    - install-base
    - python
