---
- name: SSH | add .local for hosts without fqdn
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1       {{ hostvars[inventory_hostname].ansible_hostname }}.local  {{ hostvars[inventory_hostname].ansible_hostname }}"
    state: present
  register: fqdn_fix
  become: True
  when: "'.' not in ansible_fqdn"
  tags: fqdn

- name: SSH | re-collect Ansible facts
  setup:
  when: fqdn_fix|changed
  tags: fqdn

- name: SSH | Add pub-key from config to authorized_hosts
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', ssh_pub_key_path )}}"
  register: sshkey_import
  no_log: True
  when: ssh_pub_key_path is defined

- name: SSH | Verify PubkeyAuthentication enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#?RSAAuthentication"
    regexp: "^#?PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  become: True
  register: sshauth_enabled
  notify: restart ssh
  tags: keyauth

- name: SSH | Check status of cert ssh authentication
  set_fact:
    ssh_auth: "{{ ssh_pub_key_path is defined|bool and (sshkey_import|success and sshauth_enabled|success) }}"

- name: SSH | Create ssh cert for {{ ansible_user }}
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ ansible_user }}@{{ ansible_fqdn }}"
    state: present
  no_log: True
  tags: ssh-keygen

- name: SSH | add github to known_hosts
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present
  no_log: True
  when: not ansible_check_mode
  tags:
    - add-known-hosts
    - github

- name: SSH | add gitlab to known_hosts
  known_hosts:
    name: gitlab.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa gitlab.com') }}"
    state: present
  no_log: True
  when: not ansible_check_mode
  tags:
    - add-known-hosts
    - gitlab

- name: SSH | Enable ssh ForwardAgent for repo access
  blockinfile:
    path: "/home/{{ ansible_user }}/.ssh/config"
    state: present
    create: yes
    insertbefore: EOF
    owner: "{{ ansible_user }}"
    mode: 0600
    block: |
      Host github.com
        ForwardAgent yes

      Host gitlab.com
        ForwardAgent yes
  tags: ssh-agent
